sudo: false
language: android
android:
    components:
        # SDK version
        - android-23
        # Use the latest revision of Android SDK Tools
        - tools
        # Build tools version
        - build-tools-23.0.3
        # Android Support Library (appcompat)
        - extra-android-support
        # Android Support Repository
        - extra-android-m2repository
script:
    - ./gradlew test
deploy:
  - provider: script
    script: ./deploy-gh-pages.sh
    on:
      branch: master
  - provider: script
    script: ./deploy-bintray.sh
    on:
      tags: true

env:
  global:
  # GitHub
  - secure: "hvVpRgZ9sUbM5qQcG4ZQFOMY1LmIHgnzv5CalOXl2PCHnZXF/w8+hFoaYbrN273Wq7B7WDixgOLX2uZyuq1e34w9AAD1kbz9XJz7K3RUEPQXNcGI/tcHGi8UmZK14JvqS0/oaag3INWbeQGHf/iPR1tbeW/4KUhCHj8fy04k34c="
  # Bintray
  - secure: "FuB9QFkFCHfGOdtygHwekh/bBFIiLxKAhYBEYhic8VvZjtOkVW+Epz4uuywhioMAm8dFQUJP4HemnaKekhhO1HJXTQ2dw1da6Y0+7oRO41cTR/yexsls88G+DZ0ssr/ivkzkrF3QPGl7SV0ItYhgCx7whbELAWPboxYqDzEPVJY="
